kind: pipeline
type: docker
name: Deploy (development)
trigger:
  branch:
    - main
platform:
  os: linux
  arch: amd64
steps:
  - name: Restore cache
    image: meltwater/drone-cache:dev
    pull: if-not-exists
    settings:
      access-key:
        from_secret: cache_access_key
      secret-key:
        from_secret: cache_secret_key
      restore: true
      region: us-east-1
      bucket:
        from_secret: cache_bucket
      endpoint:
        from_secret: cache_endpoint
      mount:
        - '.yarn/cache'
  - name: Build and deploy
    image: node
    commands:
      - 'npm i -g vercel@canary'
      - 'vercel pull --yes --environment=development --token $VERCEL_TOKEN'
      - 'vercel build --token $VERCEL_TOKEN'
      - 'vercel deploy --prebuilt --token=$VERCEL_TOKEN'
    environment:
      VERCEL_TOKEN:
        from_secret: vercel_token
      VERCEL_ORG_ID:
        from_secret: vercel_org_id
      VERCEL_PROJECT_ID:
        from_secret: vercel_project_id
  - name: Rebuild cache
    image: meltwater/drone-cache:dev
    pull: if-not-exists
    settings:
      access-key:
        from_secret: cache_access_key
      secret-key:
        from_secret: cache_secret_key
      rebuild: true
      region: us-east-1
      bucket:
        from_secret: cache_bucket
      endpoint:
        from_secret: cache_endpoint
      mount:
        - '.yarn/cache'
