kind: pipeline
type: docker
name: default
platform:
  os: linux
  arch: amd64
steps:
  - name: deploy-development
    image: node
    commands:
      - 'npm i -g vercel@canary'
      - 'vercel project add $VERCEL_PROJECT_ID'
      - 'vercel pull --yes --environment=development --token $VERCEL_TOKEN'
      - 'vercel build --token $VERCEL_TOKEN'
      - 'vercel build --prebuilt --token=$VERCEL_TOKEN'
    environment:
      VERCEL_TOKEN:
        from_secret: vercel_token
      VERCEL_ORG_ID:
        from_secret: vercel_org_id
      VERCEL_PROJECT_ID:
        from_secret: vercel_project_id
