kind: pipeline
type: docker
name: Deploy (development)
trigger:
  branch: 
  - main
platform:
  os: linux
  arch: amd64
steps:
  - name: Build and deploy
    image: node
    commands:
      - 'npm i -g vercel@canary'
      - 'vercel pull --yes --environment=development --token $VERCEL_TOKEN'
      - 'vercel build --token $VERCEL_TOKEN'
      - 'vercel deploy --prebuilt --token=$VERCEL_TOKEN'
    environment:
      VERCEL_TOKEN:
        from_secret: vercel_token
      VERCEL_ORG_ID:
        from_secret: vercel_org_id
      VERCEL_PROJECT_ID:
        from_secret: vercel_project_id
