name: deploy

on:
  workflow_dispatch:
  push:

permissions:
  contents: read

jobs:
  build:
    name: build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: yarn install

      - name: Build Vite React App
        run: yarn build

      - name: Copy file via ssh keychain
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          port: ${{ secrets.DEPLOY_PORT }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: dist/*
          target: ${{ secrets.DEPLOY_PATH }}