name: CI
on: 
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'
jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install node v18
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: yarn install
        run: yarn install
      - name: run eslint
        run: yarn lint
